export enum Consts {

  APPLICATIONS_CLOSED,
  APPLICATIONS_OPEN_NONE_REGISTERED,
  APPLICATIONS_OPEN_REGISTERED_ALREADY,

  APPLICATION_GET_BY_USER_ID = `https://localhost:7038/api/Applications/GetByUserId`,
}

